// tools/stamp.mjs - write a build stamp so the deployed app can detect a new
// version (GitHub Pages caches files for 10 minutes) and refresh its modules.
// Run before committing: node tools/stamp.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function listFiles(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) listFiles(p, out);
    else if (/\.(js|css)$/.test(e.name)) out.push(p);
  }
  return out;
}

const v = new Date().toISOString().replace(/[-:]/g, '').replace(/\..+/, '').replace('T', '-');
const files = listFiles(path.join(root, 'src'))
  .map((p) => './' + path.relative(root, p).split(path.sep).join('/'))
  .sort();
files.push('./index.html', './manifest.webmanifest');
fs.writeFileSync(path.join(root, 'version.json'), JSON.stringify({ v, files }, null, 2) + '\n');
fs.writeFileSync(path.join(root, 'src', 'version.js'), `// generated by tools/stamp.mjs\nexport const VERSION = '${v}';\n`);
console.log(`stamped ${v} (${files.length} files)`);
