// tools/stamp.mjs - write a build stamp so the deployed app can detect a new
// version (GitHub Pages caches files for 10 minutes) and refresh its modules,
// and a manifest of the CSVs in docs/ so the phone can load them from the
// site without the Files app. Run before committing: node tools/stamp.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseProjections, parseRankings } from '../src/csv.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function listFiles(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) listFiles(p, out);
    else if (/\.(js|css)$/.test(e.name)) out.push(p);
  }
  return out;
}

// ---- build stamp ----
const v = new Date().toISOString().replace(/[-:]/g, '').replace(/\..+/, '').replace('T', '-');
const files = listFiles(path.join(root, 'src'))
  .map((p) => './' + path.relative(root, p).split(path.sep).join('/'))
  .sort();
files.push('./index.html', './manifest.webmanifest');
fs.writeFileSync(path.join(root, 'version.json'), JSON.stringify({ v, files }, null, 2) + '\n');
fs.writeFileSync(path.join(root, 'src', 'version.js'), `// generated by tools/stamp.mjs\nexport const VERSION = '${v}';\n`);
console.log(`stamped ${v} (${files.length} files)`);

// ---- docs manifest: newest CSV of each kind (projections, rankings1qb, rankingsSuperflex) ----
const docsDir = path.join(root, 'docs');
const byKind = {};
for (const name of fs.readdirSync(docsDir)) {
  if (!/\.csv$/i.test(name)) continue;
  const full = path.join(docsDir, name);
  const text = fs.readFileSync(full, 'utf8');
  const st = fs.statSync(full);
  const head = text.slice(0, 4000);
  let kind = null;
  let rows = 0;
  try {
    if (/Consensus/.test(head)) {
      const r = parseRankings(text);
      kind = r.format === 'superflex' ? 'rankingsSuperflex' : r.format === '1qb' ? 'rankings1qb' : null;
      rows = r.count;
    } else if (/PaCom/.test(head) && /\bTar\b/.test(head)) {
      rows = parseProjections(text).count;
      kind = 'projections';
    }
  } catch (e) {
    console.log(`skipping docs/${name}: ${e.message}`);
  }
  if (!kind) continue;
  const entry = { kind, file: `docs/${name}`, name, mtime: st.mtime.toISOString(), size: st.size, rows };
  if (!byKind[kind] || byKind[kind].mtime < entry.mtime) byKind[kind] = entry;
}
const manifest = { generated: new Date().toISOString(), files: Object.values(byKind).sort((a, b) => a.kind.localeCompare(b.kind)) };
fs.writeFileSync(path.join(docsDir, 'files.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log(`docs/files.json: ${manifest.files.map((f) => `${f.kind}=${f.name} (${f.rows} rows)`).join('; ') || 'no CSVs'}`);
